---
- name: 'Manage checkmk passwords'
  hosts: "test"
  gather_facts: False
  connection: local

  tasks:
    - setup:
        gather_subset:
          - min
    # Creating and Updating is the same.
    # If passwords are configured, no_log should be set to true.
    - name: "Create a new password."
      checkmk.general.password:
        server_url: "{{server_url}}"
        site: "{{site}}"
        automation_user: "{{automation_user}}"
        automation_secret: "{{automation_secret}}"
        name: "{{item.name}}"
        title: "{{item.title}}"
        customer: "{{item.customer | default(omit)}}"
        comment: "{{ ansible_date_time.iso8601 }}: - ansible managed - {{item.comment}}"
        documentation_url: "{{item.documentation_url}}"
        password: "{{item.password}}"
        owner: "admin"
        shared: [
            "all"
        ]
        state: "{{item.state}}"
      loop: "{{ passwords|flatten(levels=1) }}"
      loop_control:
        label: "{{ item.name }}: {{item.state}}"

    - name: "Activate changes including foreign changes."
      checkmk.general.activation:
        server_url: "{{server_url}}"
        site: "{{site}}"
        automation_user: "{{automation_user}}"
        automation_secret: "{{automation_secret}}"
        force_foreign_changes: 'true'
#      run_once: 'true'